### PR TITLE
support new profile.d buildpack setup

### PR DESCRIPTION
**Pull request by tsloughter**

### CODE REVIEW

**Comment by archaelus** [comment]
Does this stuff really work? There was a subsequent pull request about it. OTP version specific?

**Comment by tsloughter** [comment]
It works and pretty sure it is necessary. I had to do this to keep the buildpack working. What other pull request?

**Comment by archaelus** [comment]
https://github.com/archaelus/heroku-buildpack-erlang/pull/7

**Comment by tsloughter** [comment]
Hah, oh, very weird we both created these at the same time.

**Pull request merged**
